import "./globals.css";
import type { Metadata } from "next";
import Modal from "@/components/Modal/Modal";
import { ToastContainer } from "react-toastify"; 
import StoreProvider from "../store/StoreProvider";
import { Geist, Geist_Mono } from "next/font/google";
import { ModalProvider } from "@/context/ModalContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ModalProvider>
          <StoreProvider>
            <ToastContainer />
            {children}
            <Modal />
          </StoreProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
